#!/bin/bash

pp="flat"

curl -X POST --data-binary @- 'http://localhost:8080/analytics/api/data/$flat' <<EOF
{"user":{"name":"andrew","start_date":"2009-11-01 00:00:00"},"sale":{"value":10.0,"qty":13}}
{"user":{"name":"sam","start_date":"2011-03-21 00:00:00"},"sale":{"value":8.0,"qty":7}}
EOF

